import 'package:cangaia_de_jegue/config/neon_config.dart';
import 'package:flutter/foundation.dart';
import 'package:postgres/postgres.dart';

class NeonAdminService {
  const NeonAdminService();

  Future<String> criarTabelas() async {
    const sql = '''
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario TEXT UNIQUE NOT NULL,
  senha TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vendas_ingressos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_comprador TEXT NOT NULL,
  telefone_comprador TEXT NOT NULL DEFAULT '',
  quantidade_ingressos INTEGER NOT NULL,
  valor_total NUMERIC NOT NULL,
  parcelamento INTEGER NOT NULL,
  usuario_vendedor TEXT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  valor_recebido NUMERIC NOT NULL DEFAULT 0,
  status_pagamento TEXT NOT NULL DEFAULT 'pendente',
  recebido_em TIMESTAMPTZ,
  camisa_entregue_em TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS recibos_pagamento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venda_id BIGINT NOT NULL REFERENCES vendas_ingressos(id) ON DELETE CASCADE,
  valor NUMERIC NOT NULL,
  recebido_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  forma_pagamento TEXT NOT NULL DEFAULT 'nao_informado'
);

CREATE TABLE IF NOT EXISTS despesas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao TEXT NOT NULL,
  valor NUMERIC NOT NULL,
  data_despesa TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS eventos_sincronizacao_pendentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_entidade TEXT NOT NULL,
  id_entidade BIGINT,
  operacao TEXT NOT NULL,
  carga JSONB,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sincronizado_em TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS tamanhos_camisa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venda_id BIGINT NOT NULL REFERENCES vendas_ingressos(id) ON DELETE CASCADE,
  tamanho TEXT NOT NULL,
  quantidade INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS pedidos_camisas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tamanho TEXT NOT NULL,
  quantidade INTEGER NOT NULL DEFAULT 1,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE vendas_ingressos
ADD COLUMN IF NOT EXISTS telefone_comprador TEXT NOT NULL DEFAULT '';

ALTER TABLE vendas_ingressos
ADD COLUMN IF NOT EXISTS camisa_entregue_em TIMESTAMPTZ;

ALTER TABLE recibos_pagamento
ADD COLUMN IF NOT EXISTS forma_pagamento TEXT NOT NULL DEFAULT 'nao_informado';
''';

    debugPrint('[SYNC] Iniciando criacao de tabelas no Neon');

    final connection = await Connection.openFromUrl(
      NeonConfig.driverConnectionUrl,
    );
    try {
      await connection.execute(
        sql,
        ignoreRows: true,
        queryMode: QueryMode.simple,
      );
      debugPrint('[SYNC] Sucesso ao criar/verificar tabelas no Neon');
      return 'Tabelas criadas/verificadas com sucesso no Neon.';
    } catch (error, stackTrace) {
      debugPrint('[SYNC] Erro ao criar tabelas no Neon: $error');
      debugPrint('[SYNC] Stacktrace: $stackTrace');
      rethrow;
    } finally {
      await connection.close();
    }
  }
}
